<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-06-07T07:15:20Z" name="Surefire suite" finished-at="2018-06-07T07:15:20Z" duration-ms="46">
    <groups>
      <group name="test-method-with-params">
        <method signature="TestCase.test(boolean, java.lang.String)[pri:0, instance:TestCase@3aefe5e5]" name="test" class="TestCase"/>
      </group> <!-- test-method-with-params -->
    </groups>
    <test started-at="2018-06-07T07:15:20Z" name="Surefire test" finished-at="2018-06-07T07:15:20Z" duration-ms="46">
      <class name="TestCase">
        <test-method signature="test(boolean, java.lang.String)[pri:0, instance:TestCase@3aefe5e5]" started-at="2018-06-07T14:15:20Z" name="test" data-provider="provider"
                     finished-at="2018-06-07T14:15:20Z" duration-ms="7" status="PASS">
          <params>
            <param index="1">
              <value>
                <![CDATA[testng: 1]]>
              </value>
            </param>
            <param index="0">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method signature="test(boolean, java.lang.String)[pri:0, instance:TestCase@3aefe5e5]" started-at="2018-06-07T14:15:20Z" name="test" data-provider="provider"
                     finished-at="2018-06-07T14:15:20Z" duration-ms="1" status="FAIL">
          <params>
            <param index="1">
              <value>
                <![CDATA[testng: 2]]>
              </value>
            </param>
            <param index="0">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[testng: 2 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: testng: 2 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- TestCase -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
